"""create_roles_and_permissions_tables

Revision ID: 56a76628c8c8
Revises: afb6d336d003
Create Date: 2026-09-21 21:00:42.081171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a76628c8c8'
down_revision: Union[str, Sequence[str], None] = 'afb6d336d003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('guard_name', sa.String(length=50), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guard_name', name='uq_permissions_name_guard_name')
    )
    op.create_index(op.f('ix_permissions_group'), 'permissions', ['group'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('guard_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guard_name', name='uq_roles_name_guard_name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('model_has_permissions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_index(op.f('ix_model_has_permissions_permission_id'), 'model_has_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_model_has_permissions_user_id'), 'model_has_permissions', ['user_id'], unique=False)
    op.create_table('model_has_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_model_has_roles_role_id'), 'model_has_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_model_has_roles_user_id'), 'model_has_roles', ['user_id'], unique=False)
    op.create_table('role_has_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index(op.f('ix_role_has_permissions_permission_id'), 'role_has_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_has_permissions_role_id'), 'role_has_permissions', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_has_permissions_role_id'), table_name='role_has_permissions')
    op.drop_index(op.f('ix_role_has_permissions_permission_id'), table_name='role_has_permissions')
    op.drop_table('role_has_permissions')
    op.drop_index(op.f('ix_model_has_roles_user_id'), table_name='model_has_roles')
    op.drop_index(op.f('ix_model_has_roles_role_id'), table_name='model_has_roles')
    op.drop_table('model_has_roles')
    op.drop_index(op.f('ix_model_has_permissions_user_id'), table_name='model_has_permissions')
    op.drop_index(op.f('ix_model_has_permissions_permission_id'), table_name='model_has_permissions')
    op.drop_table('model_has_permissions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_group'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
