"""add_role_and_department_to_users

Revision ID: afb6d336d003
Revises: 0181322ab736
Create Date: 2026-09-21 19:34:12.976353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb6d336d003'
down_revision: Union[str, Sequence[str], None] = '0181322ab736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='Doctor'))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=False, server_default='General Medicine'))
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_column('users', 'department')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
