"""update_users_table_columns

Revision ID: b2e71abde11f
Revises: 41fc16c5c4ce
Create Date: 2026-09-21 15:50:55.823880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e71abde11f'
down_revision: Union[str, Sequence[str], None] = '41fc16c5c4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add new columns safely
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=30), server_default='active', nullable=False))

    # 2. Transfer data from old columns to new columns if rows exist
    op.execute("UPDATE users SET name = COALESCE(full_name, 'User'), password = COALESCE(hashed_password, ''), status = 'active'")

    # 3. Enforce NOT NULL on name and password
    op.alter_column('users', 'name', nullable=False)
    op.alter_column('users', 'password', nullable=False)

    # 4. Create indexes
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)

    # 5. Drop deprecated columns
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_active')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'staff'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_column('users', 'status')
    op.drop_column('users', 'password')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'mobile_number')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
