"""add_account_lockout_and_otp_hashes

Revision ID: cbcd7d03266a
Revises: 3c5b44c498e4
Create Date: 2026-09-22 01:08:57.209225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcd7d03266a'
down_revision: Union[str, Sequence[str], None] = '3c5b44c498e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('token_hash', sa.String(length=64), nullable=True))
    op.add_column('password_resets', sa.Column('otp_hash', sa.String(length=64), nullable=True))
    op.alter_column('password_resets', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_password_resets_otp_hash'), 'password_resets', ['otp_hash'], unique=False)
    op.create_index(op.f('ix_password_resets_token_hash'), 'password_resets', ['token_hash'], unique=True)
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_password_resets_token_hash'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_otp_hash'), table_name='password_resets')
    op.alter_column('password_resets', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('password_resets', 'otp_hash')
    op.drop_column('password_resets', 'token_hash')
    # ### end Alembic commands ###
